### ISSUE TITLE
Indentation on Github projects

### ISSUE THREAD

**Issue by Asuza** [sindresorhus/detect-indent#14]
I'm looking for statistics on code indentation (which is the most popular by language), and can't find any. Your tool seems appropriate for finding out the answer.

Have you already tried your tool on the most popular GitHub projects, perhaps via some script that pulls down popular repositories and analyzes them?

**Comment by sindresorhus** [comment]
I have not, but that sounds like a cool use :D

**Comment by Hirse** [comment]
This seems to be in the direction that you are looking for:
[Popular Coding Convention on Github](http://sideeffect.kr/popularconvention/)

**Comment by Asuza** [comment]
That's a really cool site, @Hirse. Thanks for sharing.

**Comment by tkrotoff** [comment]
@Asuza check https://github.com/ukupat/tabs-or-spaces, it uses detect-indent :)
