### ISSUE TITLE
Consider SmartTabs indentation style

### ISSUE THREAD

**Issue by baby-gnu** [sindresorhus/detect-indent#17]
Hello,

I personally use [SmartTabs](https://www.emacswiki.org/emacs/SmartTabs) for indenting and spacing:

* tabs for indentation
* space for alignment

This is the most flexible mode since everybody see the same thing, just indentation change depending on the number of columns they configure for tabs.

Could you consider it?

Regards.

**Comment by julien-f** [comment]
What is the issue here? What would you want this module to do?

I believe that SmartTabs are correctly handled, `detect-indent` should properly detect that the indent use is a single tab, no?

**Comment by baby-gnu** [comment]
You are right, it detect a single tab, I should have verified what was said in ukupat/tabs-or-spaces#28 before opening this issue.

My apologies.

**Comment by julien-f** [comment]
I can understand that you would like the module to detect SmartTabs but it is something complex.

`detect-indent` would need to be able to detect alignments on top of detecting indentations which is not something, IMHO, that could easily be done.
