### ISSUE TITLE
Breaks as a front-end dependency

### ISSUE THREAD

**Issue by echenley** [sindresorhus/detect-indent#20]
We use this module on the front end (a wysiwyg code editor) and the recent switch to ES6 breaks in certain browsers. It's not a big deal to run babel over it, but in our case this packages is the one exception among hundreds of dependencies which are ES5 compatible. In my opinion, using this in-browser is a valid use case that should be supported.

**Comment by sindresorhus** [comment]
Stay on v4 then. There's nothing new in v5.
