### ISSUE TITLE
Detect the mix of space and tabs

### ISSUE THREAD

**Issue by vaidd4** [sindresorhus/detect-indent#23]
Hi,
For one of the project I work on, in JSON files I use tabs with an identation size of 2.  
The `.editorconfig` looks like this :  
```
[*.json]
indent_style = tab
indent_size = 2
``` 
The problem is that `npm install` re-indent the file with only tabs.
It suppose it's because more tabs are detected than spaces.

I wonder if there is a simple solution or if it is like the issue #17 about smart tabs ?
Or maybe it could try detecting an `.editorconfig` file ?

Thanks in advance

**Comment by vaidd4** [comment]
Well, it has an effect in the IDE i'm using (IDEA).
It produces an ident of 2 spaces but when there is 4 spaces it creates a tab (the tab is 4 spaces wide).
example: (note in GH tabs are 6 chars wide)
```JSON
{
  "name": "my-app",
  "version": "0.0.1",
  "license": "MIT",
  "scripts": {
	"start": "ng serve",
	"build": "ng build",
	"test": "ng test",
	"lint": "ng lint",
  }
}
```
So here, the 2 spaces are replaced by 1 tab and the tab is replaced by 2 tabs.

PS: I don't have an definitive reason why. The syntax has not been decided by me, and I'm slowly making changes.

**Comment by sindresorhus** [comment]
> It produces an ident of 2 spaces but when there is 4 spaces it creates a tab (the tab is 4 spaces wide).

That sounds like a bug in IDEA.

**Comment by sindresorhus** [comment]
Sorry, but I'm not interested in handling such a weird case. This should be fixed in the IDEA.

**Comment by vaidd4** [comment]
I don't understand why it should be a bug, it's another way to indent files like smart tabs are.
I know it's disturbing, but you can see it like this : small indentation (only 2 chars), less characters (1 tab instead of 4 spaces)

**Comment by vaidd4** [comment]
No problem, I will try to change this from my side.
Thanks for the quick responses
